### ISSUE TITLE
Check /app/package.json: command not found.

### ISSUE THREAD

**Issue by Kf637** [saul-avikar/discord-application-bot#2]
I'm getting this message in the logs, Check /app/package.json: command not found.

![eb526a7faf130c284cbd1eaf843409c5](https://user-images.githubusercontent.com/43268197/89947059-2f606000-dc24-11ea-96e0-2d5fd37889b5.png)

**Comment by saul-jb** [comment]
This repository is fairly old and has not been kept up to date, so you may wish to use a more up to date one for your purposes.

#### However if you are still intent on using it:

Glitch is looking for a start script and it is oddly specific about the naming. If you change the `"serve"` to `"start"` under `"scripts"` in **package.json** it should hopefully resolve your issue.

**Comment by Kf637** [comment]
> This repository is fairly old and has not been kept up to date, so you may wish to use a more up to date one for your purposes.
> 
> #### However if you are still intent on using it:
> Glitch is looking for a start script and it is oddly specific about the naming. If you change the `"serve"` to `"start"` under `"scripts"` in **package.json** it should hopefully resolve your issue.

Hello, I can't find "serve" under "scripts"
![0e8c95a4a8f6ffbf9239c759fc9f6f9d](https://user-images.githubusercontent.com/43268197/89953322-23c66680-dc2f-11ea-90c9-875f2d691f86.png)

**Comment by saul-jb** [comment]
Whoops, I was supposed to say to change `"bot"` to `"start"`.

**Comment by Kf637** [comment]
> Whoops, I was supposed to say to change `"bot"` to `"start"`.

Now I'm getting this error "at Object.<anonymous> (/app/index.js"
![5a51e3fde6e957168799012ea9f1f399](https://user-images.githubusercontent.com/43268197/89956128-d2b97100-dc34-11ea-8130-5c00a576d268.png)

**Comment by saul-jb** [comment]
You must install the dependencies using `npm install`. If you are using using a service that does not allow you run this directly, you will need to consult their documentation on how to install node dependencies.

**Comment by Kf637** [comment]
> You must install the dependencies using `npm install`. If you are using using a service that does not allow you run this directly, you will need to consult their documentation on how to install node dependencies.

Thanks! How do I set the bot up? The command !setup won't work

**Comment by saul-jb** [comment]
`$setup` for setup and `$help` for help. The symbol for the bots commands can be changed by altering `const botChar = "$";` in **index.js**.

**Comment by Kf637** [comment]
I've tried that, didn't work.
No respond.

**Comment by saul-jb** [comment]
Is the bot online in the discord server?

**Comment by Kf637** [comment]
Yes.

**Comment by Kf637** [comment]
It's online.

**Comment by Kf637** [comment]
> Is the bot online in the discord server?

Yes and I'm unable to add more than 3 questions.

**Comment by Kf637** [comment]
![b891aac409780d6bcfd22f03acf454e4](https://user-images.githubusercontent.com/43268197/90130270-75bfd700-dd6a-11ea-88a4-007ea8a5e400.png)

**Comment by Kf637** [comment]
Here is some more error
![da4a80f1da3b6679a16846fa0f46f0b5](https://user-images.githubusercontent.com/43268197/90131220-106ce580-dd6c-11ea-87d5-5de4370a9043.png)

**Comment by Kf637** [comment]
userToSubmitApplicationsTo.send(
                             ^
TypeError: userToSubmitApplicationsTo.send is not a function
at applicationFormCompleted (/app/index.js:22:30)
at Client.client.on.msg (/app/index.js:194:13)
    at Client.emit (events.js:189:13)
    at MessageCreateAction.handle (/rbd/pnpm-volume/4120c502-bd19-4532-a4fc-5249062306e5/node_modules/discord.js/src/client/actions/MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (/rbd/pnpm-volume/4120c502-bd19-4532-a4fc-5249062306e5/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (/rbd/pnpm-volume/4120c502-bd19-4532-a4fc-5249062306e5/node_modules/discord.js/src/client/websocket/WebSocketManager.js:386:31)
    at WebSocketShard.onPacket (/rbd/pnpm-volume/4120c502-bd19-4532-a4fc-5249062306e5/node_modules/discord.js/src/client/websocket/WebSocketShard.js:436:22)
    at WebSocketShard.onMessage (/rbd/pnpm-volume/4120c502-bd19-4532-a4fc-5249062306e5/node_modules/discord.js/src/client/websocket/WebSocketShard.js:293:10)
    at WebSocket.onMessage (/rbd/pnpm-volume/4120c502-bd19-4532-a4fc-5249062306e5/node_modules/ws/lib/event-target.js:125:16)
    at WebSocket.emit (events.js:189:13)
![2ea68841fd414ee8178436934346bba6](https://user-images.githubusercontent.com/43268197/90131415-63df3380-dd6c-11ea-8484-790514838ac6.png)
