### ISSUE TITLE
Not an issue but a question

### ISSUE THREAD

**Issue by FreshyMoon** [saul-avikar/discord-application-bot#3]
.

**Comment by FreshyMoon** [comment]
is there anyway I'm able to make the bot put submissions into a channel in a discord server and also msg through the bot and also add more things to the bot?

**Comment by saul-jb** [comment]
There is no way of doing these things without changing the code _at this time_. When I get some time I will have a look at giving it some much needed updates.

**Comment by FreshyMoon** [comment]
Alright
