### ISSUE TITLE
i have to restart the bot everytime i do a command

### ISSUE THREAD

**Issue by thevexxx** [saul-avikar/discord-application-bot#6]
so whenever i type in a command on discord it works perfectly fine but then it becomes unresponsive and i have to turn the bot off then back on for it to work again

**Comment by saul-jb** [comment]
Could you provide steps to reproduce this problem?
Does the bot stop running?

**Comment by thevexxx** [comment]
the bot stops running sorry for the late response!

**Comment by saul-jb** [comment]
Discord's api changed - should be fixed now.
