### ISSUE TITLE
Unable to Setup Admin Role

### ISSUE THREAD

**Issue by DEEJAY-CYPH3R** [saul-avikar/discord-application-bot#7]

**Comment by DEEJAY-CYPH3R** [comment]
![image](https://user-images.githubusercontent.com/73964396/99771396-14f52700-2b2f-11eb-8f41-4a66dcc67ff9.png)
Please help with this. I have the role named Admin with Admin perms but still the bot is now setting it up

**Comment by saul-jb** [comment]
You need to add the role _Admin_ to yourself through discords default method of modifying roles.
